spring:
  application:
    #代表项目里文件名称的前缀：user
    name: config-client



server:
  port: 8881


#http请求地址和资源文件映射如下
#/{application}/{profile}[/{label}]

#/{application}-{profile}.yml

#/{label}/{application}-{profile}.yml

#/{application}-{profile}.properties

#/{label}/{application}-{profile}.properties